# Generated by Django 4.2.3 on 2023-09-26 19:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import document_library.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Category name', max_length=512)),
                ('description', models.CharField(blank=True, help_text='Category description', max_length=512, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(help_text='Document name', max_length=512)),
                ('document', models.FileField(default=None, help_text='Document URL', max_length=512, null=True, upload_to=document_library.models.set_filename)),
                ('description', models.TextField(blank=True, default='', help_text='Photo description')),
                ('title', models.CharField(blank=True, help_text='Title', max_length=512, null=True)),
                ('author', models.CharField(blank=True, help_text='Author', max_length=512, null=True)),
                ('type_license', models.CharField(blank=True, choices=[('sense-llicencia', 'Sense llicència'), ('copyright', 'Copyright'), ('copyleft', 'Copyleft'), ('cc-by', 'Reconeixement'), ('cc-by-nc', 'Reconeixement – NoComercial'), ('by-nc-sa', 'Reconeixement - NoComercial - CompartirIgual'), ('by-nc-nd', 'Reconeixement - NoComercial - SenseObraDerivada'), ('by-sa', 'Reconeixement - CompartirIgual'), ('by-nd', 'Reconeixement - SenseObraDerivada'), ('publica', 'Publica')], default='sense-llicencia', help_text='License type', max_length=30, null=True)),
                ('expiry_date', models.DateTimeField(help_text='Date on which the deletion of the photo is scheduled', null=True)),
                ('visible', models.BooleanField(default=True, help_text='The file is visible on Internet')),
                ('category', models.ForeignKey(blank=True, help_text='Document category', null=True, on_delete=django.db.models.deletion.PROTECT, to='document_library.documentcategory')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
