#!/usr/bin/env sh

set -o errexit
set -o nounset

case "$1" in
webserver)
  # Default value for upstream "api" service hostname
  export API_SERVICE_HOSTNAME="${API_SERVICE_HOSTNAME:-api}"
  echo "*** Using '$API_SERVICE_HOSTNAME' as upstream api hostname"
  envsubst \$API_SERVICE_HOSTNAME < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf
  echo "*** Running nginx"
  nginx -g 'daemon off;'
  ;;

*)
  exec "$@"
  ;;
esac
