# Generated by Django 4.2.3 on 2023-09-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(help_text='Creation datetime of the operation.', verbose_name='Creation datetime')),
                ('system', models.CharField(default=None, help_text='System on which the operation depends.', max_length=64, null=True, verbose_name='System')),
                ('subsystem', models.CharField(default=None, help_text='Subsystem on which the operation depends.', max_length=64, null=True, verbose_name='Subsystem')),
                ('log_id', models.CharField(default=None, help_text='Identification of the affected object', max_length=64, null=True, verbose_name='Identification')),
                ('action', models.CharField(default=None, help_text='Action.', max_length=256, null=True, verbose_name='Action')),
                ('description', models.CharField(help_text='Description of the action executed.', max_length=1024, verbose_name='Description')),
                ('url', models.TextField(help_text='URL called for the execution of the action.', verbose_name='Url address')),
                ('http_get_parameters', models.TextField(default=None, help_text='GET parameters received by the server.', null=True, verbose_name='GET Parameters')),
                ('http_post_parameters', models.TextField(default=None, help_text='POST parameters received by the server.', null=True, verbose_name='POST Parameters')),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('HEAD', 'HEAD'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='get', help_text='HTTP method.', max_length=32, verbose_name='HTTP method')),
                ('http_user_agent', models.CharField(help_text='User agent that sends the browser to the server.', max_length=1024, verbose_name='Client user agent')),
                ('ip', models.GenericIPAddressField(help_text='IP address of the client that executes this action.', null=True, verbose_name='IP adress')),
                ('executor_user', models.IntegerField(help_text='User who has made the operation.', null=True, verbose_name='User who has made the operation')),
                ('extra', models.TextField(default=None, help_text='Extra data', null=True, verbose_name='Extra data')),
                ('is_staff', models.BooleanField(default=False, help_text='Action taken by personnel of the application', verbose_name='Action taken by personnel of the application')),
                ('response', models.TextField(default=None, help_text='Response of the action', null=True, verbose_name='Response of the action')),
                ('status_code', models.CharField(default=None, help_text='HTTP response status', max_length=32, null=True, verbose_name='HTTP response status')),
            ],
            options={
                'verbose_name': 'Action log',
                'verbose_name_plural': 'Actions log',
                'ordering': ['-creation_datetime', 'system'],
                'permissions': (('view_all', 'View registered actions'), ('view_all_staff', 'View action registered by staff')),
                'indexes': [models.Index(fields=['creation_datetime', 'system', 'subsystem', 'action'], name='actionloggi_creatio_45ef3f_idx')],
            },
        ),
    ]
