# Generated by Django 4.2.3 on 2024-01-30 19:14

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='User email')),
                ('first_name', models.CharField(max_length=30, null=True, verbose_name='User first name')),
                ('last_name', models.CharField(max_length=150, null=True, verbose_name='User last name')),
                ('role', models.CharField(choices=[('superadmin', 'Superadministrador'), ('user', 'User')], default='user', verbose_name='User role')),
                ('phone', models.CharField(max_length=16, null=True, verbose_name='User phone number')),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='Is user active')),
                ('deactivation_datetime', models.DateTimeField(null=True, verbose_name='Datetime when user was deactivated')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='User date joined')),
                ('login_attempts', models.PositiveIntegerField(default=0, verbose_name='User login attemps')),
                ('last_bad_login_attempt_datetime', models.DateTimeField(null=True, verbose_name='Last bad login attempt datetime')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserResetPassword',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used', models.BooleanField(default=False, verbose_name='This token has been used')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='The user who owns the token')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
