from user.constants import *

USER_ROLES = (
    (ROLE_SUPERADMIN_KEY, ROLE_SUPERADMIN_STR),
    (ROLE_ADMIN_KEY, ROLE_ADMIN_STR),
    (ROLE_REFERENT_KEY, ROLE_REFERENT_STR),
    (ROLE_MANAGER_KEY, ROLE_MANAGER_STR),
    (ROLE_QUERY_KEY, ROLE_QUERY_STR),
)
