# Generated by Django 4.2.3 on 2024-01-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Ingredient name')),
                ('quantity', models.PositiveIntegerField(verbose_name='Ingredient quantity')),
                ('unit', models.CharField(verbose_name='Measure unit')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Food name')),
                ('description', models.CharField(verbose_name='Food description')),
                ('image', models.ImageField(null=True, upload_to='repice/', verbose_name='Recipe image')),
                ('diners', models.PositiveIntegerField(verbose_name='Diners number')),
                ('time', models.PositiveIntegerField(verbose_name='Cooking time in minutes')),
                ('category', models.ManyToManyField(blank=True, to='food.recipecategory', verbose_name='Food categories')),
                ('ingredients', models.ManyToManyField(blank=True, to='food.recipeingredient', verbose_name='Food ingredients')),
            ],
        ),
    ]
