# Generated by Django 4.2.3 on 2024-01-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.FileField(null=True, upload_to='repice/', verbose_name='Recipe image'),
        ),
    ]
